# Generated by Django 5.2.8 on 2026-03-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Database', 'Database'), ('Tools', 'Tools')], max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('proficiency', models.PositiveSmallIntegerField(default=80)),
            ],
            options={
                'ordering': ['category', 'id'],
            },
        ),
    ]
